### ISSUE TITLE
Length Calculator

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#1]
This calculator converts meter to kilometer.

**Comment by rko0211** [comment]
hello, i want to contribute on this project. it will be my first opensource contribution . please assign me this issue

**Comment by S-ishita** [comment]
@rko0211 this should be assigned to me only.

**Comment by Srijita-Mandal** [comment]
@S-ishita Please raise your issues after the contribution period starts. I can't assign as it is created before.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC
