### ISSUE TITLE
Ui enhancement 

### ISSUE THREAD

**Issue by kushaljgec2025** [Srijita-Mandal/fix-your-nums#100]
1. adding a hover effect on few buttons,
2. And also enhance the Ui of calculation page according the home ui .
![Screenshot 2023-02-18 225312](https://user-images.githubusercontent.com/108950724/219879634-557511a7-43e7-4e61-b544-ccffebdcb6cc.png)
![Screenshot 2023-02-18 225350](https://user-images.githubusercontent.com/108950724/219879635-9ee7abe6-6da9-45ce-8b7b-ea176e5bf37c.png)

**Comment by kushaljgec2025** [comment]
I want to work on this under jwoc plss assign me.

**Comment by deepbeatz** [comment]
@Srijita-Mandal I want to work on this under JWOC

**Comment by Srijita-Mandal** [comment]
@kushaljgec2025 Go for it.
It's not needed to add the hover effect to the buttons of `Home` page.
Enhance the UI of the calculation pages. Don't make the design too much complicated. Match the pages with the Home page theme and fonts.

You can show me after do it for one page. I'll give the review.
All the best.

**Comment by Srijita-Mandal** [comment]
@kushaljgec2025 are you working on it? Or i'll unassign you..

**Comment by kushaljgec2025** [comment]
You can unassigned me.

**Comment by deepbeatz** [comment]
@Srijita-Mandal i want to work on this issue under JWOC

**Comment by priyanka1551** [comment]
@Srijita-Mandal I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@deepbeatz you go for it. Don't make the design too much complicated. Match the pages with the Home page theme and fonts.

**Comment by Code1705** [comment]
want to contribute to this issue by changing the UI specifically background colour and fonts of the landing page, please assign me under JWOC.

**Comment by Srijita-Mandal** [comment]
@deepbeatz are you working on it? Or i'll unassign you..

**Comment by deepbeatz** [comment]
yes i am very sorry, i was inactive because of illness, i am working on it from today.... thanks for waiting so much

**Comment by deepbeatz** [comment]
@Srijita-Mandal 
i have done the following:
1. hover zoom effect on "try now" buttons
2. hover zoom effect on back to top button
3. hover zoom effect on footer links: home, jwoc, calculators

shall i raise pr?

**Comment by deepbeatz** [comment]
lets do the ui designing of the calculation pages in a separate issue, it will be better for both of us....... here i have done the ui enhancement of the home page........once u say , i will create a separate issue for the ui enhancement of calculation pages and u can assign me there and plz do keep the appropriate labels there........thanks

**Comment by Srijita-Mandal** [comment]
@deepbeatz 

I can't give you `hard` tag for this change. It was for improving all calculator pages.

**Comment by deepbeatz** [comment]
You can ofcourse change the tag to medium
