### ISSUE TITLE
Make landing page mobile responsive

### ISSUE THREAD

**Issue by AK-shat-JAIN** [Srijita-Mandal/fix-your-nums#108]
@Srijita-Mandal I can try to make the landing page mobile responsive 
you can assign this task to me

**Comment by Rubyseher** [comment]
I am interested to fix this issue , I am participating under JWOC. Can you assign me this issue?

**Comment by Srijita-Mandal** [comment]
> @Srijita-Mandal I can try to make the landing page mobile responsive you can assign this task to me

Go for it.

**Comment by AK-shat-JAIN** [comment]
@Srijita-Mandal thanks for merge 
This issue can be closed now
