### ISSUE TITLE
Currency Converter Bug

### ISSUE THREAD

**Issue by swarnade** [Srijita-Mandal/fix-your-nums#109]
When We Type In The Currency Converter ,The 1 Remains Constant.

**Comment by Srijita-Mandal** [comment]
@swarnade Go for it. There are some more calculators which have the same bug- default input 1. Check the rest calculators also and resolve it.

**Comment by swarnade** [comment]
Changed The Default Of Calculator From "1" To Null Of "Algebraic Derivative Calculator" & "Currency Converter"
