### ISSUE TITLE
Trigonometric Calculator

### ISSUE THREAD

**Issue by EmberTSeal** [Srijita-Mandal/fix-your-nums#11]
Currently the project does not have a section for trigonometric calculations. 
I would like to add this section - where the user can find trig values for a given angle.
Please assign this issue to me, thank you.

**Comment by Srijita-Mandal** [comment]
@EmberTSeal Please raise your issues after the contribution period starts. I can't assign as it is created before.

**Comment by SasiVardhan247** [comment]
I want to work on this issue under JWOC

**Comment by Harry629** [comment]
I want to work on this issue under JWOC

**Comment by EmberTSeal** [comment]
> @EmberTSeal Please raise your issues after the contribution period starts. I can't assign as it is created before.

Please assign me this issue now.
