### ISSUE TITLE
Add weight conversions to fix-your-nums

### ISSUE THREAD

**Issue by dibyendu02** [Srijita-Mandal/fix-your-nums#113]
Add a weight conversions feature which would help to convert between different units of weight

**Comment by dibyendu02** [comment]
I want to work under JWOC

**Comment by Srijita-Mandal** [comment]
@dibyendu02 Go for it.
Please add the features that are already added to the other calculators. Like-
1.  Dark theme
2.  Back to home button
3.  RESET button.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @Srijita-Mandal
