### ISSUE TITLE
Bottom to top button

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#114]
Make a bottom to top button for the `Home` page, which will be appeared after some scrolling.

**Comment by sarkartanmay393** [comment]
@Srijita-Mandal I would like to work on it

**Comment by Srijita-Mandal** [comment]
@sarkartanmay393 Go for it.

**Comment by priyanka1551** [comment]
I would like to work on it under JWOC

**Comment by LuckySingh9897** [comment]
I would Like to work on this issue under JWOC.

**Comment by sarkartanmay393** [comment]
#119

**Comment by vatan-prakash** [comment]
Please assign me this issue under jwoc @Srijita-Mandal Srijita-Mandal

**Comment by Awesomeasma** [comment]
@Srijita-Mandal 
I would like to work on this issue under JWOC.
Please assign this issue to me.
