### ISSUE TITLE
Data Convertor is not responsive and dark mode is also not there

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#121]
I want to work on this issue under JWOC @Srijita-Mandal 
![Screenshot (138)](https://user-images.githubusercontent.com/105537443/220191756-53f87c43-a693-4407-926e-a999bfeb5373.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it. Also enhance the overall UI of the page.

**Comment by priyanka1551** [comment]
> @priyanka1551 Go for it. Also enhance the overall UI of the page.

okay

**Comment by priyanka1551** [comment]
@Srijita-Mandal di weight convertor is also not responsive. Can you change the easy label to medium label so that I can make each page responsive
![Screenshot (140)](https://user-images.githubusercontent.com/105537443/220411341-1557ac46-3b5c-41b8-878d-939bc97ded7a.png)


> @priyanka1551 Go for it. Also enhance the overall UI of the page.

**Comment by priyanka1551** [comment]
@Srijita-Mandal please change the tag because there are many things to do in this

> @Srijita-Mandal di weight convertor is also not responsive. Can you change the easy label to medium label so that I can make each page responsive ![Screenshot (140)](https://user-images.githubusercontent.com/105537443/220411341-1557ac46-3b5c-41b8-878d-939bc97ded7a.png)
> 
> > @priyanka1551 Go for it. Also enhance the overall UI of the page.

**Comment by vatan-prakash** [comment]
Please assign me this issue under jwoc

**Comment by priyanka1551** [comment]
> Please assign me this issue under jwoc

I did it already. Search for more issues there
