### ISSUE TITLE
Design enhahcement througout the calculators making them more interactive and eye catching.

### ISSUE THREAD

**Issue by rohhhit31** [Srijita-Mandal/fix-your-nums#122]

**Comment by rohhhit31** [comment]
Assign me this issue than i'll start my work on the UI enhancement of the internal calculator pages of the website.

**Comment by Srijita-Mandal** [comment]
@rohhhit31 Go for it.

**Comment by rohhhit31** [comment]
Sure.

**Comment by pooranjoyb** [comment]
Assign me this issue. Would like to work onto it. @Srijita-Mandal
