### ISSUE TITLE
Add permutaion and combination calculator

### ISSUE THREAD

**Issue by dibyendu02** [Srijita-Mandal/fix-your-nums#125]
want to implement the permutation and combination calculator

**Comment by Srijita-Mandal** [comment]
@dibyendu02 Go for it.
Please follow the UI of hcf-lcm calculator and do validations for the inputs.

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @Srijita-Mandal

**Comment by vatan-prakash** [comment]
i want to contribute in this issue under JWOC please assign  it to me @Srijita-Mandal

**Comment by Awesomeasma** [comment]
@Srijita-Mandal 
I would love to work on this issue under JWOC.
Please assign this issue to me ....

**Comment by priyanka1551** [comment]
Please assign this issue to the people in the queue. As this issue was assigned 3 days ago to @dibyendu02  but it is an easy issue so only 24 hours should be given to solve this issue
