### ISSUE TITLE
Enhancing binary-2-decimal page into a Base converter

### ISSUE THREAD

**Issue by pooranjoyb** [Srijita-Mandal/fix-your-nums#131]
# Reason/Context
## Why we need this improvement?
In this current version of this conversion page, there's a facility only to convert from binary to decimal or vice versa but there isn't any mention of other base conversions like octal to hexa, Hexa to binary, binary to octal, etc

## How will this change help?
It will enhance the functionality of the webpage. It will ensure that people would be able to use this webpage for different types of base conversions.

### What changes have to be introduced?

The following to be added : 
- [x] Binary to Octal and vice-versa
- [x] Hexadecimal to binary and vice-versa
- [x] Octal to Hexadecimal and vice versa

### Will this be a breaking change?
No, it won't be breaking any changes.

### How could it be implemented/designed?
This can be achieved by adding more functions to carry out the operations, eventually giving a better user service from the website. 

### Related screenshots : 
![enhance](https://user-images.githubusercontent.com/90945182/220641793-7c9454f3-2823-4ca7-a851-b5f3b9c6d306.png)

**Comment by Srijita-Mandal** [comment]
@pooranjoyb Go for it.
You have mentioned 3 additional conversions. Do one more-  `Hexadecimal to Decimal and vice-versa`.

**Comment by pooranjoyb** [comment]
On it! 🚀

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @Srijita-Mandal
