### ISSUE TITLE
Weight Converter is not responsive and Javascript is also not linked with html file

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#133]
I want to work on this issue under JWOC @Srijita-Mandal 
![Screenshot (143)](https://user-images.githubusercontent.com/105537443/220657292-81dec4d0-969d-4724-a366-7e02cb4e0e9b.png)

**Comment by Harry629** [comment]
I would like to work on this issue under JWOC.

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it. Also enhance the UI. Change the buttons UI and the result showing position. Add the name of the calculator above the pink box. Follow the UI of `Data Converter`.

**Comment by priyanka1551** [comment]
> @priyanka1551 Go for it. Also enhance the UI. Change the buttons UI and the result showing position. Add the name of the calculator above the pink box. Follow the UI of `Data Converter`.

okay di

**Comment by priyanka1551** [comment]
> > @priyanka1551 Go for it. Also enhance the UI. Change the buttons UI and the result showing position. Add the name of the calculator above the pink box. Follow the UI of `Data Converter`.
> 
> okay di

The output of the above issue is as follows:
![Screenshot (145)](https://user-images.githubusercontent.com/105537443/220929562-4d96d591-bbcb-4388-b5cb-3bb2263a72dc.png)

**Comment by priyanka1551** [comment]
The output of the above issue is as follows:
![Screenshot (145)](https://user-images.githubusercontent.com/105537443/220929848-fbfd54e0-0a20-4e10-baf7-58c0242b34dd.png)
