### ISSUE TITLE
Num to Word converter

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#134]
This will convert a Number to a word.

for example :-
100 to one hundred 
2 to two

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Upto how much upperlimit of numbers you can do it?

**Comment by LuckySingh9897** [comment]
@Srijita-Mandal  up to  1 Trillion.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Okay go for it.
