### ISSUE TITLE
Trigonometric calculator is not working correctly

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#136]
Here, It is giving the result for only sine trigonometric function and in case of other functions too such as cot, cosec it is giving the same result. Check all option is also not working correctly. On checking all the options , sine output is generated only.
I want to work on this issue under JWOC @Srijita-Mandal 
![Screenshot (147)](https://user-images.githubusercontent.com/105537443/220931095-bfca8277-9ffc-47e3-9209-8abb1b7b8827.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it. And also Clear the result as well while clicking the Reset button.

**Comment by priyanka1551** [comment]
> @priyanka1551 Go for it. And also Clear the result as well while clicking the Reset button.

mam , can I remove check all option. Because, in actual calculators also one function is calculated at one time

**Comment by priyanka1551** [comment]
The output for the above issue is shown here. Please merge my pr @Srijita-Mandal 
![Screenshot (149)](https://user-images.githubusercontent.com/105537443/221282144-a637def7-c8c7-4b2f-8bd0-c6aa986bea26.png)
