### ISSUE TITLE
Add steps for contributing in Readme.md

### ISSUE THREAD

**Issue by Arbtrage** [Srijita-Mandal/fix-your-nums#137]
Want to add steps for contributing in Readme.md . Beginners face the problem of finding the proper steps to contribute to an Open Source project, like basic git commands and what to do when there is a merge conflict with there Pull Request .

Would like to add proper steps with screenshots. 

@Srijita-Mandal , please assign me this issue under JWOC .

**Comment by Srijita-Mandal** [comment]
@Arbtrage Go for it.
Implement these in `CONTRIBUTING.md` and link `CONTRIBUTING.md` in Readme file.

**Comment by Akshayp02** [comment]
> @Arbtrage Go for it. Implement these in `CONTRIBUTING.md` and link `CONTRIBUTING.md` in Readme file.

could you assign me this issue will provide proper steps to contribute to from fork to push with proper images snap shot.

**Comment by Arbtrage** [comment]
I am already and working on it . @Akshayp02

**Comment by Akshayp02** [comment]
okay no problem.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC
