### ISSUE TITLE
enhancement in nav bar, add logo beside home, calc and about button. fix the paragraph by giving padding margin in landing page

### ISSUE THREAD

**Issue by Shantanu-Meta** [Srijita-Mandal/fix-your-nums#138]

**Comment by Srijita-Mandal** [comment]
@Shantanu-Meta Go for it. Make sure it remains responsive.

**Comment by Shantanu-Meta** [comment]
hey @Srijita-Mandal , currently i am a bit busy but 
i am ensuring you i will submit it before monday evening.  Sorry for the delay

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by Shantanu-Meta** [comment]
hey i am working on it and it is assigned to me currently @vk20july

**Comment by Shantanu-Meta** [comment]
> @Shantanu-Meta Make PR before tonight. Else I'll assign next one.

I have made the pr, I am really sorry about the delay. From further I will put my extra effort to mke the website more charming and attractive. Kindly check the pr and let me know if any enhancement is required.

**Comment by Srijita-Mandal** [comment]
> > @Shantanu-Meta Make PR before tonight. Else I'll assign next one.
> 
> I have made the pr, I am really sorry about the delay. From further I will put my extra effort to mke the website more charming and attractive. Kindly check the pr and let me know if any enhancement is required.

Yeah! Merged your PR.
