### ISSUE TITLE
Sales Tax Calculator

### ISSUE THREAD

**Issue by neokd** [Srijita-Mandal/fix-your-nums#139]
Hey , I would like to work on this issue under **JWOC**.

The Sales Tax Calculator would compute , input as  before-tax price, sale tax rate, and output as final, or after-tax price.

**Comment by Srijita-Mandal** [comment]
@neokd go for it.

**Comment by neokd** [comment]
Thanks

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC

**Comment by neokd** [comment]
can we use cdn for tailwind css?
