### ISSUE TITLE
Adding Currency Converter

### ISSUE THREAD

**Issue by subratkumar46** [Srijita-Mandal/fix-your-nums#14]
Currency Converter : It will take amount as an input from user and also ask user from which currency to which currency they want to convert , then it will display the result according to given inputs.

I would like to add this feature in this project .
I want to work on this issue under JWOC
Please assign this issue to me.

**Comment by PrachiSingh66** [comment]
Hii, I want to work on this issue under JWOC so please assign it to me.
Thank you

**Comment by Srijita-Mandal** [comment]
@subratkumar46 Go for it. All the best.

**Comment by subratkumar46** [comment]
@Srijita-Mandal Currency Converter will use API to convert currency . The user will get nearly 150 currrency options to choose from . Implementing this is quite lengthy so can I get a medium batch :)

**Comment by Srijita-Mandal** [comment]
Okay, take time and implement it properly.

> @Srijita-Mandal Currency Converter will use API to convert currency . The user will get nearly 150 currrency options to choose from . Implementing this is quite lengthy so can I get a medium batch :)

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC
