### ISSUE TITLE
Bug In Power Calculator -- Base Value Input.......

### ISSUE THREAD

**Issue by swarnade** [Srijita-Mandal/fix-your-nums#140]
Default Value Of "Base" Of Power Calculator Is Set To 1 .By Default The value Should be Null ....... #jwoc
https://srijita-mandal.github.io/fix-your-nums/power.html

**Comment by Srijita-Mandal** [comment]
@swarnade Yes. Fix it.

**Comment by swarnade** [comment]
Done
