### ISSUE TITLE
Retirement Calculator

### ISSUE THREAD

**Issue by Priyamakeshwari** [Srijita-Mandal/fix-your-nums#142]
Retirement Calculator can help a person plan the financial aspects of retirement. Each calculation can be used individually for quick and simple calculations, or in chronological order as a more comprehensive walkthrough of retirement planning.

I would like to work on this under JWOC pls assign to me

**Comment by Srijita-Mandal** [comment]
@Priyamakeshwari Please describe a more what you want to implement.

**Comment by Priyamakeshwari** [comment]
I would like to implement like 

- How much do you need to retire?
- How can you save for retirement?
- How much can you withdraw after retirement?

Basically i want to implement the 10%, 80%, 4% rule.

**Comment by Srijita-Mandal** [comment]
@Priyamakeshwari Go for it. Add necessary `js` inside html file or a separate js file. Avoid adding in `script.js

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @Srijita-Mandal
