### ISSUE TITLE
Make the title clickable

### ISSUE THREAD

**Issue by zugzwang03** [Srijita-Mandal/fix-your-nums#143]
When you click on the title of the website, it redirects to the homepage. So whichever segment you are in of the website, you can easily return to home page with one click.
![image](https://user-images.githubusercontent.com/95460021/220983966-6cb3a5d6-038b-4c1d-a456-686cce11ee9e.png)
I want to add this feature under JWOC'23.

**Comment by Srijita-Mandal** [comment]
@zugzwang03 Go for it.
