### ISSUE TITLE
Add pre-loader

### ISSUE THREAD

**Issue by khushimarothi** [Srijita-Mandal/fix-your-nums#149]
Want to add preloader before  landing page .
please assign under jwoc

**Comment by khushimarothi** [comment]
@Srijita-Mandal

**Comment by khushimarothi** [comment]
@Srijita-Mandal Please atleast respond.

**Comment by Srijita-Mandal** [comment]
@khushimarothi Go for it. share deployed link from your branch while making your PR.

**Comment by khushimarothi** [comment]
https://khushimarothi.github.io/fix-your-nums/

**Comment by khushimarothi** [comment]
please check it here will make a pr later
