### ISSUE TITLE
Dark mode Issue in Caesar Cipher Calculator

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#150]
Dark mode is not working in Caesar Cipher Calculator.

**Comment by S-ishita** [comment]
Please assign this issue to me under JWOC.

**Comment by Srijita-Mandal** [comment]
@S-ishita Go for it. Enable dark mode also in SIP calculator.

**Comment by S-ishita** [comment]
should i do it in two different branches for sip calculator and caesar cipher calculator or in same branch??
@Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
> should i do it in two different branches for sip calculator and caesar cipher calculator or in same branch?? @Srijita-Mandal

Do in a single branch
