### ISSUE TITLE
Mobile responsiveness || Hamburger menu

### ISSUE THREAD

**Issue by ritika728** [Srijita-Mandal/fix-your-nums#154]
Hey, I would like to open this issue under JWOC. I wish to make this properly responsive by adding a hamburger menu for the mobile view and adjusting the responsiveness of the rest. Thank you!

![photo](https://user-images.githubusercontent.com/91181981/221246823-52c3c82d-a150-4ef9-8bac-262c95e7b9e9.jpeg)

**Comment by Saishreekouda** [comment]
can i work on this?

**Comment by Srijita-Mandal** [comment]
@ritika728 Go for it
