### ISSUE TITLE
Roman Numeral To Integer Calculator

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#16]
This calculator converts any roman numeral to corresponding integer.

![Screenshot from 2023-02-14 23-41-15](https://user-images.githubusercontent.com/104543751/218822673-89461f06-745c-4478-baf9-e80ec933b4e2.png)

**Comment by S-ishita** [comment]
I want to work on this issue under JWOC.

**Comment by Srijita-Mandal** [comment]
@S-ishita I have already assigned you to 3 issues. Complete them first. Otherwise I can't assign you more.

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under jwoc.

**Comment by mecivil** [comment]
I want to work on this issue

**Comment by Harry629** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@ManasaKaza Go for it. Do Roman to integer and vice-versa also. All the best.

**Comment by S-ishita** [comment]
Hey @Srijita-Mandal this issue should be assigned to me for atleast two days.Also it was mentioned by organisers that mentee can have 4 issues at a single time from same repository.

**Comment by ManasaKaza** [comment]
Hi @S-ishita , It was mentioned that a mentee can contribute to 4 issues from different projects and 1 issue from a repo at the same time, kindly check once and correct me if I am wrong
