### ISSUE TITLE
Better UI for Hero Section

### ISSUE THREAD

**Issue by Saishreekouda** [Srijita-Mandal/fix-your-nums#165]
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/96722257/221350076-e2e56320-811e-4cf7-81b7-0fa04dd731fd.png">
The nav bar width and alignment can be improved and the way the Fix your Nums is showing on the hero page can be made better too.

**Comment by Saishreekouda** [comment]
hey @Srijita-Mandal i would like to make these changes

**Comment by Srijita-Mandal** [comment]
@Saishreekouda go for it.

**Comment by Srijita-Mandal** [comment]
@Saishreekouda make PR before tonight. Else I'll assign next one.

**Comment by Saishreekouda** [comment]
@Srijita-Mandal yes working on it
