### ISSUE TITLE
Add custom css scrollbar

### ISSUE THREAD

**Issue by Arbtrage** [Srijita-Mandal/fix-your-nums#17]
Would like to add a custom css scrollbar which would improve the UI of the website.
@Srijita-Mandal , please assign me this .

**Comment by priyanka1551** [comment]
@Srijita-Mandal I want to work on this issue under JWOC

**Comment by PrachiSingh66** [comment]
Hii, I want to work on this issue under JWOC so please assign it to me.
Thank you

**Comment by Srijita-Mandal** [comment]
@Arbtrage Go for it. All the best.
