### ISSUE TITLE
Wind Chill Calculator

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#178]
This calculator estimates the temperature felt by the body as a result of wind speed and actual air temperature and gives general advice based on the estimated temperature on how to stay warm and safe in varying degrees of low temperatures and avoid serious risks to a person's health.

**Comment by S-ishita** [comment]
Please assign this issue to me under JWOC

**Comment by Srijita-Mandal** [comment]
This is not that type of calculator which have been implemented here. Here basically mathematical calculators and conversion methods are added.
