### ISSUE TITLE
Improve landing page UI by adding animations and transitions

### ISSUE THREAD

**Issue by shloksuman** [Srijita-Mandal/fix-your-nums#18]
@Srijita-Mandal Please assign this to me

**Comment by PrachiSingh66** [comment]
I want to work on this issue under JWOC so please assign it to me

**Comment by shloksuman** [comment]
@Srijita-Mandal I would like to improve the layout and design by adding design as well as some interactive card like elements which will make the page more interactive. 
If you allow, I would request you to label this as Medium or Hard because it may take me 2-3 days to get this done. 😅

**Comment by Srijita-Mandal** [comment]
@shloksuman Go for it. Make changes only for index page i.e.- ```index.html```. Don't make any separate page.

**Comment by shloksuman** [comment]
Understood. I won't make any separate page but since I am doing the changes in UI so I would require to make changes in "indexstyle.css" file. Is that fine?

**Comment by Srijita-Mandal** [comment]
Sure. You can make changes in any file, I just told don't create any new page.

> @Srijita-Mandal Understood. I won't make any separate page but since I am doing the changes in UI so I would require to make changes in "indexstyle.css" file. Is that fine?

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC

**Comment by Shantanu-Meta** [comment]
After the task, I would like to be assigned this issue.

**Comment by shloksuman** [comment]
@Srijita-Mandal Changes have been made in UI.

- added navbar
- hero section
- bg animation
- improved cards
- animated footer section

[changeUI.webm](https://user-images.githubusercontent.com/77777064/219611042-7a3f54d8-0b58-468d-a186-51f89101b899.webm)

**Comment by Srijita-Mandal** [comment]
@shloksuman You have done it really great. Just one thing, it's not seems responsive. Can you please make it responsive and add the favicon in the `index` page?

**Comment by shloksuman** [comment]
Made the page responsive : 
![responsive1](https://user-images.githubusercontent.com/77777064/219845578-1a03281d-bb06-411d-9304-ad2ece670a5e.PNG)
![responsive2](https://user-images.githubusercontent.com/77777064/219845582-75e194da-fca7-449c-a1f9-43bcb0f53350.PNG)
![responsive3](https://user-images.githubusercontent.com/77777064/219845584-0180b308-9a9e-410b-87bb-8ee59b4bfd5d.PNG)
