### ISSUE TITLE
Roots of quadratic and cubic equation

### ISSUE THREAD

**Issue by RishabhJain0721** [Srijita-Mandal/fix-your-nums#180]
Making a calculator to calculate roots of quadratic and cubic equations.

**Comment by RishabhJain0721** [comment]
Could you assign this to me?

**Comment by Srijita-Mandal** [comment]
Quadratic equation calculator is already present. Make a calculator for cubic equations.

**Comment by RishabhJain0721** [comment]
Alright @Srijita-Mandal 

> Quadratic equation calculator is already present. Make a calculator for cubic equations.

**Comment by RishabhJain0721** [comment]
Hi @Srijita-Mandal 
I have raised a PR regarding this issue.Could you please review it?
Here is the PR link : https://github.com/Srijita-Mandal/fix-your-nums/pull/202
