### ISSUE TITLE
Add EMI Calculator

### ISSUE THREAD

**Issue by TuhinBanerjee31** [Srijita-Mandal/fix-your-nums#183]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
Please describe a more what you want to implement.

**Comment by TuhinBanerjee31** [comment]
Want to add a classic EMI (Equated Monthly Installment) calculator which will take three params. principle amount, rate of interest, and time period for total repayment. And will result in the amount which will be required every month.

**Comment by Srijita-Mandal** [comment]
@TuhinBanerjee31 Go for it.
