### ISSUE TITLE
Fix Files and Folders

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#188]
@Srijita-Mandal  I want to work on this issue under JWOC.
All the files of this repo should be arranged in a good manner as they are not beginner friendly. It will be difficult for users to find the code as the names are not easily understood and also very difficult to find in this big folder. There should be seperate folder for each html, css and js. These folder should contains seperate files of each calculator so that it become easy to understand. These files as yo can see below are just messed up. 
![Screenshot (161)](https://user-images.githubusercontent.com/105537443/221430485-67c50690-0d2c-48cf-adb1-1cba32c6ce1e.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it. Make sure all the pages, css, js, images are properly linked.
Attach deployed link from your branch while making a PR.

**Comment by priyanka1551** [comment]
@Srijita-Mandal di, It will take upto 4-5 days.So,it will be better if you could change difficulty level to hard.

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Take your time. Do the changes. I'll raise the difficulty level while merging if I think so.

**Comment by priyanka1551** [comment]
> @priyanka1551 Take your time. Do the changes. I'll raise the difficulty level while merging if I think so.

Okayy di thankuu

**Comment by priyanka1551** [comment]
@Srijita-Mandal Is there any shortcut to remove all the merge conflcit in just on go
