### ISSUE TITLE
Caesar Cipher Calculator

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#19]
The Caesar Cipher technique is one of the earliest and simplest method of encryption technique. It’s simply a type of substitution cipher, i.e., each letter of a  given text is replaced by a letter some fixed number of positions (offset) down the alphabet.

![Screenshot from 2023-02-15 00-03-40](https://user-images.githubusercontent.com/104543751/218826957-f992153d-58c5-437d-96a4-2492c4ee39ae.png)

**Comment by S-ishita** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@S-ishita Go for it.
