### ISSUE TITLE
overscrolling of page

### ISSUE THREAD

**Issue by Laxmankohar** [Srijita-Mandal/fix-your-nums#191]
when inside any calculator, the page starts overscrolling which may cause poor user experince.
I would like to work on this issue under JWOC. Can you please assign it ot me?

![image](https://user-images.githubusercontent.com/73365025/221472894-e689b57c-2e4c-4248-9691-b73e0c55301d.png)
![image](https://user-images.githubusercontent.com/73365025/221472901-ca0bbc62-8e6a-4bcc-a3e2-c4b4f0967030.png)

**Comment by Srijita-Mandal** [comment]
@Laxmankohar Some pages need to scroll vertically. Don't change the css for all the pages. Use internal css to fix the pages you think scrolling is not needed.
