### ISSUE TITLE
Convert Binary to decimal and vice-versa

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Srijita-Mandal/fix-your-nums#192]
Project Name : - Binary To Decimal 
Decription : This is simple calci that will help to covert binary number into decimal and vice-versa, It has automatic changing capabilities to display output result.

please refer the attachment
![Screenshot (189)](https://user-images.githubusercontent.com/73521123/221489025-f0211e44-789e-4f1b-8e2e-29f3a244c9ae.png)

**Comment by Kumar-Ankit56** [comment]
@Srijita-Mandal  please assign me under jwoc

**Comment by Srijita-Mandal** [comment]
This is present already.
