### ISSUE TITLE
Algebric Integral Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#195]
An algebric term in the form of ax^b where a and b are two real number
this calculator will find the integral of the expression with respect to the x.

for ex= 2x^4;
result will be = 0.4x^5

**Comment by LuckySingh9897** [comment]
I would Like to work on this issue under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Go for it.
