### ISSUE TITLE
The factorial calculator  is not working for large numbers so i want to imporve this.

### ISSUE THREAD

**Issue by KrunalGupta02** [Srijita-Mandal/fix-your-nums#20]
I want to improve the logic behind the factorial for larger numbers

**Comment by Srijita-Mandal** [comment]
@KrunalGupta02 Sure. Go for it. All the best.

**Comment by Codey001** [comment]
I want to work on this issue under JWOC

**Comment by KrunalGupta02** [comment]
@Srijita-Mandal i have made a PR plz review it and if any changes needed let me know and and merge it with jwoc label
