### ISSUE TITLE
Simple Interest Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#204]
it will calculate the simple interest and the amount after a certain period of time like after taking input as amount, rate, and time.
for ex= 
p=1000
r=12.5%
t=2
Simple interest= 250
Amount = 1250

**Comment by LuckySingh9897** [comment]
and I will also Compound interest feature in this.
I want to Work on this issue under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Implement both in same calculator.
