### ISSUE TITLE
Scroll up button

### ISSUE THREAD

**Issue by JasonDsouza212** [Srijita-Mandal/fix-your-nums#211]
- The scroll button at the bottom appears to be partially hidden behind the card
-  Instead, the button should remain visible on the card when scrolling the page

![Screenshot from 2023-03-01 10-55-04](https://user-images.githubusercontent.com/74404894/222054281-fdb962da-7b1f-4209-bbe0-bbc034973ff7.png)

## The scroll-up button is not visible
- The scroll-up button becomes invisible when we reach the bottom of the page, as it is hidden behind another button
- It would be beneficial if the scroll-up button is placed on the footer for better visibility.

![Screenshot from 2023-03-01 10-55-15](https://user-images.githubusercontent.com/74404894/222054277-6c4cfc62-e8f2-45a1-96a7-f02f8fa1d0d2.png)

**Comment by Srijita-Mandal** [comment]
@JasonDsouza212 Go for it.

**Comment by JasonDsouza212** [comment]
Fixed it

**Comment by JasonDsouza212** [comment]
![Screenshot from 2023-03-02 10-53-53](https://user-images.githubusercontent.com/74404894/222338545-16ae961c-3199-409d-9229-c85a29e32891.png)
![Screenshot from 2023-03-02 10-54-01](https://user-images.githubusercontent.com/74404894/222338535-6de2261d-7dae-4aa6-b496-0844413e14f8.png)
