### ISSUE TITLE
Add profit/loss calculator

### ISSUE THREAD

**Issue by Laxmankohar** [Srijita-Mandal/fix-your-nums#214]
The profit/loss calculator allows users to enter the cost price and selling price of a product or service, and then calculates and displays the profit or loss, along with the percentage of profit or loss. The user can click the "Calculate" button to perform the calculation.

**Comment by Laxmankohar** [comment]
I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by Srijita-Mandal** [comment]
@Laxmankohar Go for it.

**Comment by Laxmankohar** [comment]
@Srijita-Mandal , Please  have a look and confirm it sothat i can make PR.

![image](https://user-images.githubusercontent.com/73365025/222883639-8b2a0e13-55af-4663-a9a2-e66e8c782ca1.png)
![image](https://user-images.githubusercontent.com/73365025/222883759-fe51e559-2ee4-43c9-91f2-d9aa5e9c17e7.png)
![image](https://user-images.githubusercontent.com/73365025/222883763-71537981-3533-476c-bb9f-94e1e94aa301.png)

**Comment by Srijita-Mandal** [comment]
Yeah! Make your PR
