### ISSUE TITLE
Finding Differentiation of a polynomial function f(x)

### ISSUE THREAD

**Issue by pooranjoyb** [Srijita-Mandal/fix-your-nums#225]
### I would like to work on this issuer under JWOC 2023. Please Assign @Srijita-Mandal 😄

**Comment by Srijita-Mandal** [comment]
@pooranjoyb Can you implement it by improving `algebraic derivative calculator` which is already present?

**Comment by pooranjoyb** [comment]
Okk sure, I'll do that. Please assign.

**Comment by Srijita-Mandal** [comment]
> Okk sure, I'll do that. Please assign.@Srijita-Mandal

Go for it.
