### ISSUE TITLE
Fix BMI chart

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#23]
In BMI calculator, there is a issue with the BMI chart. It is not of proper size and loading slowly. Make a table with the information of the chart and replace it with the image.

**Comment by AshutoshSingh2021** [comment]
Please assign this issue to me under jwoc.

**Comment by purbakundu** [comment]
i want to contribute

**Comment by Srijita-Mandal** [comment]
@AshutoshSingh2021 Go for it. All the best.

**Comment by Codey001** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC

**Comment by itsshahinhere** [comment]
I want to work on this issue under JWOC
