### ISSUE TITLE
Linking of all the pages to the home page

### ISSUE THREAD

**Issue by ManasaKaza** [Srijita-Mandal/fix-your-nums#231]
When I open a specific calculator, it is showing 'can't reach this page, I want to link all the calculators to the home pageso that one can reach to that specific calculator

I want to work on this issue under JWOC

**Comment by ayushi1709-20** [comment]
please assign this issue to me under JWOC

**Comment by Srijita-Mandal** [comment]
@ManasaKaza please describe what you want to do.

**Comment by ManasaKaza** [comment]
@Srijita-Mandal sorry last time when I checked it showed me an error when I tried to open a specific calculator, but its fine now, it might be a network issue from my side
