### ISSUE TITLE
Testimonial UI

### ISSUE THREAD

**Issue by ritika728** [Srijita-Mandal/fix-your-nums#232]
Hey @Srijita-Mandal , I would like to open this issue under JWOC. The testimonial page UI do not matches the home page. I would like to improve this.

**Comment by Srijita-Mandal** [comment]
@ritika728 Go for it. Also add the `navbar` to the page.

**Comment by ritika728** [comment]
@Srijita-Mandal should I add the footer too ?

**Comment by Srijita-Mandal** [comment]
> @Srijita-Mandal should I add the footer too ?

No, footer is not need to be added

**Comment by ritika728** [comment]
Okay
