### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#236]
Add a search bar in the home page, which search the operation name and the respective card will come first.

**Comment by TuhinBanerjee31** [comment]
I want to work on this issue under JWOC

**Comment by zugzwang03** [comment]
I can also work on this under JWOC as all my assigned work are done now.

**Comment by Srijita-Mandal** [comment]
@TuhinBanerjee31 Go for it.
