### ISSUE TITLE
Mass conversion from kg to pounds, g, etc.

### ISSUE THREAD

**Issue by Saishreekouda** [Srijita-Mandal/fix-your-nums#241]
I would like to work on this under jwoc

**Comment by zugzwang03** [comment]
I can work on this under JWOC'23. @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
mass converter is already present.
And @Saishreekouda Don't create more than one issue at a time. You are allowed to work only on one issue of a particular project at a time.
