### ISSUE TITLE
Area conversion from acres to square metre, etc.

### ISSUE THREAD

**Issue by Saishreekouda** [Srijita-Mandal/fix-your-nums#242]
I would like to work on this under jwoc.

**Comment by Srijita-Mandal** [comment]
@Saishreekouda Go for it.

**Comment by zugzwang03** [comment]
3 days already got over for this from the date of assignment, can I work on this issue under JWOC'23 now? @Srijita-Mandal

**Comment by Saishreekouda** [comment]
Hey @zugzwang03 im working on it, i was a little busy with my college exams

**Comment by Srijita-Mandal** [comment]
> Hey @zugzwang03 im working on it, i was a little busy with my college exams

@Saishreekouda Do it by today. Otherwise I have to assign the next one.

**Comment by Saishreekouda** [comment]
@Srijita-Mandal okay ill get it done
