### ISSUE TITLE
Design Error

### ISSUE THREAD

**Issue by swarnade** [Srijita-Mandal/fix-your-nums#248]
No About Us{Footer},Present in Testimonial Page....

**Comment by Srijita-Mandal** [comment]
@swarnade please describe what you want to do.

**Comment by swarnade** [comment]
As Like In Main Page The Footer Is Present ,The All The Navigation Link Bar ,Social Bar , Description Bar

i Would Like To Just Clone It And Place It In Testimonial Bar Section

 so It Could Have Its Own. Footer Bar And Could Nice

**Comment by Srijita-Mandal** [comment]
Okay. Go for it.

**Comment by swarnade** [comment]
Integrated Footer In Page
