### ISSUE TITLE
UI of landing page needs to be upgraded.

### ISSUE THREAD

**Issue by Shantanu-Meta** [Srijita-Mandal/fix-your-nums#25]
1. The name of the website is in center which looks so unprofessional, Needs to be upgrade with clickable to load the page, also as it is a open source project, we have to add a github logo link to this project on nav bar. 
2. The footer contains copy right disclaimer is not up to date and it is not looking professional. 

i hope this needs  enhancement , kindly assign me this issue if you feel its relevant otherwise please do ignore it.

*Header part*

![image](https://user-images.githubusercontent.com/117648930/218850600-911bf5b3-f3c5-4d2b-9a6d-2cd8657fe468.png)

*Footer part*
![image](https://user-images.githubusercontent.com/117648930/218850759-f68ade21-dd27-4492-a6ec-30258744856d.png)

How it will look>>  p.s== more enhancement will be done 
![image](https://user-images.githubusercontent.com/117648930/218854469-8842c80d-3e99-467e-9361-33d836f0eba0.png)

**Comment by Srijita-Mandal** [comment]
@Shantanu-Meta This page is already assigned to improve. So may be I can assign you after that implementation.

**Comment by Codey001** [comment]
I want to work on this issue under JWOC

**Comment by AgnishaDe** [comment]
I want to contribute in this under JWOC

**Comment by sandeeprawat28** [comment]
Please assign this issue to me

**Comment by Shantanu-Meta** [comment]
> @Shantanu-Meta This page is already assigned to improve. So may be I can assign you after that implementation.

okay then if you feel to improve let me know
