### ISSUE TITLE
Average Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#254]
As far as I know, there is no calculator in this repo that take a large number of inputs so;

in this calculator, I will take the size of the array as input and then all the elements as inputs, and then find the average of all numbers

for eg;---
input --    size of array = 5
                  elements = 10 12 13 6 14
output ---   11

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Go for it.
