### ISSUE TITLE
Remove 1 about  button 

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#262]
@Srijita-Mandal  As you can see on the top right corner, there are 2 about buttons . I want to remove one button which is of no use and make top part responsive according to that
![Screenshot (186)](https://user-images.githubusercontent.com/105537443/223032174-facc85d7-a907-4b6f-b0f5-e16a1f027aaf.png)

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
@priyanka1551 this has been fixed from another issue. Please find some other.

**Comment by priyanka1551** [comment]
> @priyanka1551 this has been fixed from another issue. Please find some other.

Okayyyy
