### ISSUE TITLE
GPA converter

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#268]
This calculator calculate a student grade when student enters the marks in particular subjects.

**Comment by S-ishita** [comment]
Please assign this issue to  me under JWOC

**Comment by Srijita-Mandal** [comment]
@S-ishita But the grading system is not same everywhere. Rather can you implement CGPA to percentage converter and vice-versa?

**Comment by S-ishita** [comment]
ok i will implement gpa converter

**Comment by Srijita-Mandal** [comment]
@S-ishita Yes. Go for it.
