### ISSUE TITLE
Reset Button in Retirement Calculator(Phase 2)

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#270]
I want to work on this issue under JWOC phase 2 @Srijita-Mandal 
I want to add reset button in retirement calculator and also the alignment of input box of initial investment is not proper , I want to fix it.
![Screenshot (192)](https://user-images.githubusercontent.com/105537443/223174200-af907ac4-60ab-427c-b4db-b61242c9e9c7.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it.
