### ISSUE TITLE
[Feature] Standard Deviation Calculator

### ISSUE THREAD

**Issue by pooranjoyb** [Srijita-Mandal/fix-your-nums#271]
#### I will add a function that will calculate the standard deviation of the given sample using the following formula : 
![demo19](https://user-images.githubusercontent.com/90945182/223177200-b4f78d07-fccf-4ccd-8281-6ed07a11e1e4.png)

## Would be glad if you'd assign me this issue. @Srijita-Mandal 😄 👍

**Comment by Srijita-Mandal** [comment]
@pooranjoyb Quality issue 👍 
Go for it.
