### ISSUE TITLE
Nth Root Calculator is added two times (Phase 2)

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#273]
As you can see Nth root calculator is added two times in the page on left side. I want to remove one. I want to work on this issue under JWOC phase 2 @Srijita-Mandal 
![Screenshot (193)](https://user-images.githubusercontent.com/105537443/223197895-76aaec0a-9d8c-4199-ae57-d26e43d2c5ab.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Raise one issue at a time. I can't assign more than one at a time.

**Comment by priyanka1551** [comment]
> @priyanka1551 Raise one issue at a time. I can't assign more than one at a time.

I had made pr for that . Please merge it and assign this issue to me.

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Yes. Go for the issue #273

**Comment by Srijita-Mandal** [comment]
Please take a `git pull` before make your PR. Otherwise some conflicts can be occurred as the folder structure has been changed.

**Comment by priyanka1551** [comment]
This has been solved by someone else I think. When I take git pull , there is only 1 calculator. So, you can close this issue @Srijita-Mandal
