### ISSUE TITLE
Mean Median Mode Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#275]
In this, we take the sample as input from the user 
and then return the mean, median, and mode ,all three results in a single calculator.

for example 
input ---  
size of sample= 5
sample    = 2 4 6 2 1

output=== mean = 3
                   median= 2
                   mode=2

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Yes. Go for it.

**Comment by SarveshGholap** [comment]
I want to work under jwoc under this issue

**Comment by SarveshGholap** [comment]
I want to work on these issue under jwoc
