### ISSUE TITLE
Create Error Page

### ISSUE THREAD

**Issue by TuhinBanerjee31** [Srijita-Mandal/fix-your-nums#276]
It is required to have a responsive error page for the website. 
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@TuhinBanerjee31 Go for it. Match the theme with the home page.

**Comment by Srijita-Mandal** [comment]
Please take a `git pull` before make your PR. Otherwise some conflicts can be occurred as the folder structure has been changed.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
