### ISSUE TITLE
Horse Power Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#285]
There are two methods to calculate the horsepower of a vehicle
1. Elapsed time Method
2. Trap speed Method
#For Elapsed method 
we take input as **vehicle weight** and **time is taken to complete a 1/4 mile**
then calculate the horsepower.
#For Trap speed method
we take input as **vehicle weight** and **speed at the crossing of 1/4 mile** and then calculate the horsepower.
I can make a calculator on either method or both methods in one calculator under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Go for it. Implement both.
