### ISSUE TITLE
Would Like to Make The Testimonial Page ,Button More Realistic

### ISSUE THREAD

**Issue by swarnade** [Srijita-Mandal/fix-your-nums#286]

**Comment by deepbeatz** [comment]
@Srijita-Mandal assign me this issue under jwoc

**Comment by Srijita-Mandal** [comment]
@swarnade Go for it.

**Comment by Srijita-Mandal** [comment]
Please take a `git pull` before make your PR. Otherwise some conflicts can be occurred as the folder structure has been changed.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by Srijita-Mandal** [comment]
@swarnade You are assigned 2days ago. Create your PR asap or I have to assign the nest one.

**Comment by Srijita-Mandal** [comment]
@deepbeatz you are assigned for this.

**Comment by swarnade** [comment]
@Srijita-Mandal Due to Some Issue i Was Unable To Solve it.. Looking Forward For other Issues

**Comment by deepbeatz** [comment]
@Srijita-Mandal can u plz tell me which buttons do i have to improve the css of in the testimonials page????

**Comment by deepbeatz** [comment]
@Srijita-Mandal are u there ? plz let me know what type of a change u want.....

**Comment by deepbeatz** [comment]
@Srijita-Mandal pr sent
