### ISSUE TITLE
Update the about section

### ISSUE THREAD

**Issue by zugzwang03** [Srijita-Mandal/fix-your-nums#288]
There are only 28 calculators listed in the about section, but in reality there are more than 48 calculators in the recent version, I want to update this and also in the card of yours, the description contains lorem ipsum text, I can fix that with your LinkedIn about maybe or whatever you feel appropriate under JWOC'23.
![image](https://user-images.githubusercontent.com/95460021/223634045-f40e265b-a9fc-465c-abac-eb85a9b81511.png)
![image](https://user-images.githubusercontent.com/95460021/223634118-667f36a0-7858-46ed-857c-fcb19dea0666.png)

**Comment by Srijita-Mandal** [comment]
@zugzwang03 Yeah add the calculators. And change the styling of the profile card and any other change in css you want to do.
