### ISSUE TITLE
Update README file with contributors list

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#30]
Update `README.md` file with the contributors list. Add the section after `Contact`.

**Comment by Arbtrage** [comment]
@Srijita-Mandal ,please assign me this issue .

**Comment by Srijita-Mandal** [comment]
Yes! Go for it.

**Comment by Codey001** [comment]
I want to work on this issue under JWOC

**Comment by Arbtrage** [comment]
> Yes! Go for it. Also add stat badges of issues, forks and stars of the repo.

@Srijita-Mandal , okay will start working on it .
