### ISSUE TITLE
Add area calculator

### ISSUE THREAD

**Issue by zugzwang03** [Srijita-Mandal/fix-your-nums#304]
I want to add an area calculator which can calculate the area of a square by taking the side as input, rectangle by taking its length and breadth, rhombus by taking its sides, triangle by taking its base and height, etc. under JWOC'23. Note that area calculator and area unit convertor are different in its operations.

**Comment by Srijita-Mandal** [comment]
@zugzwang03 Yes go for it.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
