### ISSUE TITLE
Income Tax Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#306]
It will take your annual income as input
and gives the output  as tax you have to give and how much is left with you

for ex--
input == 300000
output===
tax=  15000
take home salary= 285000

(as for different salary range different percentage of tax is issued by the Indian government.)
 
A sales tax calculator is present in this repo so I want to add an income tax calculator also.
Please assign me this under JWOC.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
