### ISSUE TITLE
Rank of a matrix calculator

### ISSUE THREAD

**Issue by madmaverickminion** [Srijita-Mandal/fix-your-nums#307]
I want to add a calculator for calculating the rank of a matrix. 
input -: n,m
and a matrix of order nXm 
returns an integer

Please assign this issue to me under JWOC

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by Srijita-Mandal** [comment]
@madmaverickminion Make your PR by tomorrow. Or I have to assign next one.

**Comment by Srijita-Mandal** [comment]
@Awesomeasma you are assigned for this issue.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@Awesomeasma Add the calculator in the Home page and a new PR.

**Comment by Awesomeasma** [comment]
> @Awesomeasma Add the calculator in the Home page and a new PR.

@Srijita-Mandal 
I have added it to the homepage, please review...

**Comment by Awesomeasma** [comment]
> @Awesomeasma you are assigned for this issue.

@Srijita-Mandal 
Now that it's done, can u please close this issue ?
