### ISSUE TITLE
Add a New Favicon 

### ISSUE THREAD

**Issue by AnkitMajee** [Srijita-Mandal/fix-your-nums#31]
Web icon for the site

**Comment by Srijita-Mandal** [comment]
@AnkitMajee Go for it.

**Comment by Codey001** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC

**Comment by AnkitMajee** [comment]
## I  got some design of the Favicon tell me if you need any change before the PR
## 1
![FYN1](https://user-images.githubusercontent.com/76817118/219284287-b53b3c1c-9cc2-4934-b2f8-eb777db0901b.png)
## 2
![FYN2](https://user-images.githubusercontent.com/76817118/219284489-ce7ed521-a7a4-427d-b61b-7d5081955d87.png)
## 3
![FYN3](https://user-images.githubusercontent.com/76817118/219284604-6bab2ae4-b7df-4dcf-8444-db3f793cda3d.png)
## 4
![FYN4](https://user-images.githubusercontent.com/76817118/219284612-6d502ad0-91e1-46d2-95ab-7bac4592ee9d.png)
## 5
![FYN5](https://user-images.githubusercontent.com/76817118/219284615-56c3fc49-e88d-4f55-b976-e94c64ca86ec.png)
## 6
![FYN6](https://user-images.githubusercontent.com/76817118/219284623-4f557c87-92fe-4e6a-9791-f95625d1b80b.png)

**Comment by Pritam991** [comment]
check my PR please.

**Comment by Pritam991** [comment]
I want to working on this. Already i made a PR.

**Comment by Srijita-Mandal** [comment]
> 

@AnkitMajee Go with design no. 6

**Comment by Srijita-Mandal** [comment]
> I want to working on this. Already i made a PR.

But I didn't assign you. I can't merge your PR @Pritam991

**Comment by AnkitMajee** [comment]
Ok making the PR @Srijita-Mandal
