### ISSUE TITLE
Add reset button in Caesar Cipher (Phase2)

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#313]
@Srijita-Mandal  I want to work on this issue under JWOC
![Screenshot (199)](https://user-images.githubusercontent.com/105537443/224053146-f78b9d4c-d1d0-4dd1-99f0-6e85fa76e432.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 go for it. Also improve the css of the page.

**Comment by priyanka1551** [comment]
Okay I can change the css of this page but please change tag as it will take more effort @Srijita-Mandal

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by priyanka1551** [comment]
> Okay I can change the css of this page but please change tag as it will take more effort @Srijita-Mandal
It is giving error in this js code also. So, I am also improving this so kindly change tag @Srijita-Mandal 
![Screenshot (201)](https://user-images.githubusercontent.com/105537443/224214420-cc193752-8d0f-4909-b902-c5abf4764e71.png)
