### ISSUE TITLE
[Feature] Adding a Button to Continue Calculation in Simple Calculator

### ISSUE THREAD

**Issue by pooranjoyb** [Srijita-Mandal/fix-your-nums#318]
# Description

#### A user might need to consecutively add or multiply or do anything with the number he/she entered continuously without entering new values. But the simple Calculator is designed in such a way that the user needs to retype the number in the input field to carry out the operation once again.

# Demonstration : 

[demo30.webm](https://user-images.githubusercontent.com/90945182/224089862-0210b475-c960-4c29-bef5-0f675c85dafb.webm)

**Comment by Srijita-Mandal** [comment]
@pooranjoyb Do you mean for addition or multiplication of more than 2 numbers?

**Comment by pooranjoyb** [comment]
> @pooranjoyb Do you mean for addition or multiplication of more than 2 numbers?

Yes

**Comment by Srijita-Mandal** [comment]
> > @pooranjoyb Do you mean for addition or multiplication of more than 2 numbers?
> 
> Yes Can I work on this one?

Yes. @pooranjoyb Go for it.
