### ISSUE TITLE
Bug Fix in many Calculators

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#319]
I want to fix some bugs like in a few calculators 
like--Integration, Derivation, Complex Modulo/argument, Standard Deviation , Complex number calculators
reset buttons are not present in this calculator so I want to add a reset button .

and in the pythogorous theorem Calculator CSS is not loading you can check it. 
<img width="1120" alt="Screenshot 2023-03-09 221059" src="https://user-images.githubusercontent.com/82679510/224093099-f698098e-fc8e-4019-a972-65d6ed9157ce.png">

I want to fix all these bugs under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Go for it.
