### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by ritika728** [Srijita-Mandal/fix-your-nums#323]
Hey @Srijita-Mandal, I would like to open this issue under JWOC. I wish to add a contact us page:
- a user can submit his information and message to communicate with the admin. 
- the page will have same UI as home page & will contain the contact form with illustrations
- it will be responsive
- it will be added in the navbar of all the pages
- the contact form will be validated

**Comment by ManasaKaza** [comment]
I would like to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@ritika728 Go for it.
