### ISSUE TITLE
Add CSS to Pythagoras theorem calculator

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#325]
This is how the pythagoras theorem calculator is looking . I want to improve its UI. 
I want to work on this issue under JWOC @Srijita-Mandal 
![Screenshot (202)](https://user-images.githubusercontent.com/105537443/224220708-85dd3dba-1a28-4397-b3b4-d32c09d4787d.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 This is has been created. Please find some other.

**Comment by priyanka1551** [comment]
> @priyanka1551 This is has been created. Please find some other.

okay
