### ISSUE TITLE
Add Reset button in Standard Deviation calculator

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#326]
I want to work on this issue under JWOC @Srijita-Mandal 
![Screenshot (203)](https://user-images.githubusercontent.com/105537443/224223325-ead06a46-3a93-4029-98cd-88d19cc0542a.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 This is also included in the issue #319  :")
Check issue #327

**Comment by priyanka1551** [comment]
> @priyanka1551 This is also included in the issue #319 :") Check issue #327

OKayyyy

**Comment by priyanka1551** [comment]
But , It doesn't include energy calc bug... Can I create issue for that?

**Comment by Srijita-Mandal** [comment]
> But , It doesn't include energy calc bug... Can I create issue for that?

Yeah. You can create.
