### ISSUE TITLE
Improve Area Calculator

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#327]
In area calculator, all types of polygon takes the input `side` and `side`. It needs to be changed one single `side` input for Square and Rhombus. Input placeholder `base` and `height` for Triangle. Also add the area of  `Circle`, `trapezium` with proper input field.

**Comment by zugzwang03** [comment]
Can I work on this issue under JWOC'23?

**Comment by Srijita-Mandal** [comment]
@zugzwang03 Sure. Go for it.
