### ISSUE TITLE
Improve Energy Calculator bug(Phase 2)

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#330]
@Srijita-Mandal I want to work on this issue under JWOC
The dark theme icon and home page icon is not properly displayed. And, also the color of the topic energy convertor is not matching with other themes
![Screenshot (204)](https://user-images.githubusercontent.com/105537443/224225060-d71b54ec-c266-4d30-84e5-277b8126731f.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it.
