### ISSUE TITLE
Change the title of area convertor

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#333]
These two are different calculators. One is to calculate area of any polygon and one converts the units of area . These are named same. So, I want to work on this issue under JWOC @Srijita-Mandal 
![Screenshot (207)](https://user-images.githubusercontent.com/105537443/224233335-78ac5d73-5c3d-4094-8303-3b03c366feec.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it. Also change the title inside the calculator. And same for the volume converter and calculator.
