### ISSUE TITLE
Prime Factor Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#335]
It will take a number as an input and then output its distinct prime factors.

for example1==
input= 100
output= 2,5

example2==
input= 25
output = 5

**Comment by LuckySingh9897** [comment]
I want to work on this under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 yes. Go for it.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
