### ISSUE TITLE
perimeter calculator

### ISSUE THREAD

**Issue by SHYALI** [Srijita-Mandal/fix-your-nums#339]
it calculates the perimeter of square, rectangle ,Parallelogram and of different shapes 
please assign me this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@SHYALI Go for it.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by SHYALI** [comment]
@Awesomeasma  I have already raised the PR
