### ISSUE TITLE
Remove the output on clicking the reset button in BMI calc (Phase 2)

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#349]
After clicking the reset button, the output is still there, I want to remove this @Srijita-Mandal 
I want to work on this issue under JWOC .
![Screenshot (210)](https://user-images.githubusercontent.com/105537443/224360135-12caea4f-174b-4ed6-a594-1755367ae1fe.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it. Also make the page scrolling about y-axis.

**Comment by priyanka1551** [comment]
other calculator pages are not scrollable ,so I will raise new issue for that

> @priyanka1551 Go for it. Also make the page scrolling about y-axis.
