### ISSUE TITLE
Improvement in the Age calculator

### ISSUE THREAD

**Issue by goresai19** [Srijita-Mandal/fix-your-nums#35]
## Description
 In the age calculator , after giving an upcoming date or a date which is not happened yet as a input the age calculator is showing a message  "welcome to earth ! Its first day on the earth ! "  
So ,I would like to fix this issue .

## Additional feature
Also If I allowed to fix this issue I will add an additional feature in the age calculator to calculate all the Days, months from a starting date to the ending date which are given by the user.
I want to contribute to this issue ,please assign me this issue . I am contributor under JWOC

**Comment by Aniket-011** [comment]
Please assign me this issue under JWOC

**Comment by Harry629** [comment]
Please assign me this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@goresai19 Go for it. Improve age calculator. And create a separate feature `Calculate Days` and implement what you mentioned in additional feature. 
Make sure create separate branch and do `git pull`.
