### ISSUE TITLE
Improve UI of Temperature calculator

### ISSUE THREAD

**Issue by anurag8546** [Srijita-Mandal/fix-your-nums#352]
In the calculator, style the "Reset" and "Submit" buttons also use placeholders for input box and output box.

**Comment by anurag8546** [comment]
@Srijita-Mandal Would like to work on this issue under JWOC.

**Comment by Srijita-Mandal** [comment]
@anurag8546 Go for it.

**Comment by anurag8546** [comment]
@Srijita-Mandal  updated.
