### ISSUE TITLE
improve the UI of the factorial calculator.

### ISSUE THREAD

**Issue by taniaban2712** [Srijita-Mandal/fix-your-nums#353]

**Comment by taniaban2712** [comment]
i want to work on this issue under JWOC.

**Comment by Srijita-Mandal** [comment]
@taniaban2712 What type of improvement?

**Comment by taniaban2712** [comment]
![image](https://user-images.githubusercontent.com/110692684/224411585-7bd45fc1-b59d-4b9f-b6db-93535e325156.png)
the ui is very simple and also, i want to enhance the button.

**Comment by Srijita-Mandal** [comment]
@taniaban2712 Go for it.

**Comment by taniaban2712** [comment]
Hello, I am seeing that the UI of almost all the calculators are quite basic.
I changed the UI of the factorial by giving some hover lights and made the buttons animated
LIGHT MODE:
![image](https://user-images.githubusercontent.com/110692684/224429060-f5220985-9dc2-4904-a18d-688e5340bc53.png)
![image](https://user-images.githubusercontent.com/110692684/224429132-11ab6fb1-dddc-4c28-96d0-4c6dfce8af17.png)
DARK MODE:
![image](https://user-images.githubusercontent.com/110692684/224429202-5aa9f25d-d8b4-40ed-a5df-9c70fcc3d3bb.png)
![image](https://user-images.githubusercontent.com/110692684/224429234-bac773fc-8f8e-4314-b435-b51f9b47c48c.png)

can I create another issue by changing the UI of all the pages in the same way?
(also, please do tell if enhancements to be made)

**Comment by Srijita-Mandal** [comment]
Can you match the theme with the home page theme?

**Comment by taniaban2712** [comment]
the theme of the homepage was glowy neon lights. Will try to match that. I am telling this because the calculators dont match the original homepage.

**Comment by taniaban2712** [comment]
should i do this?

**Comment by taniaban2712** [comment]
should i push the initial changes only? please do respond.

**Comment by taniaban2712** [comment]
please do respond if i should push my code.

**Comment by Srijita-Mandal** [comment]
@taniaban2712 make your PR. please use discord channel to communicate. It's not possible always to open all issues.

**Comment by taniaban2712** [comment]
closing this issue as i have made a new issue regarding this.
