### ISSUE TITLE
Fixing errors in Console(Phase 2)

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#360]
Console is showing error in script.js at line no 739,736 and 757.....If these errors are not fixed, this may show its effect in future calculators that are to be built. I would like to work on this issue under JWOC
![Screenshot (212)](https://user-images.githubusercontent.com/105537443/224461915-ad406a1a-95ec-4b2b-97ed-b5afa06c0c72.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Yes. go for it.
