### ISSUE TITLE
Srijita Mandal -"Web Icon Does Not Redirect to their Specific Location"

### ISSUE THREAD

**Issue by swarnade** [Srijita-Mandal/fix-your-nums#365]

**Comment by Srijita-Mandal** [comment]
@swarnade please describe what you mean.

**Comment by swarnade** [comment]
The Social Link Of Your "About Us" Of The Srijita Mandal "Profile Card" Does Not Work

**Comment by Srijita-Mandal** [comment]
This has been solved by another issue.
