### ISSUE TITLE
[Feature] Adding Submission Endpoint to Contact Us

### ISSUE THREAD

**Issue by pooranjoyb** [Srijita-Mandal/fix-your-nums#370]
## Screenshot : 
![demo39](https://user-images.githubusercontent.com/90945182/224482412-4f72ca5b-98b8-498a-9ed9-932e16e6984a.png)

## Outcomes : 
- The messages will be delivered to the user's email address directly through the redirections of the website.
- **No PHP, NodeJS, Express Server or any backend code required**

## Implementation : 
- I would be using a third party website called [FormSubmit](https://formsubmit.co) who will do the work for us.
- We will connect our form to `FormSubmit` endpoint and they'll email you the submissions directly to your Email Address

### I would like to work on this issue under JWOC 2023. Please assign 😄 @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
@pooranjoyb yes. go for it.
