### ISSUE TITLE
Distance Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#372]
There are two methods to calculate the distance between two points.
1. when speed and time are given 
2. when coordinates of two points are given

for example==
method 1;
speed =10km/hr
time=2hr
output   === distance =20km
method 2
first point coordinates are 2,4
the second point coordinates are1,2
output  ==  distance = 2.23

I can make calculator on any of the method or both the method in same calculator under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 implement inside same calculator.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
