### ISSUE TITLE
Reset Button of some calculators are not working properly(Phase 2)

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#373]
@Srijita-Mandal reset button of sales tax calculator and profit/ loss calculator is not working properly. They are showing output even after clicking reset button. I want to fix it
I would like to work on this issue under JWOC ![Screenshot (216)](https://user-images.githubusercontent.com/105537443/224486641-494366b2-ffb8-4d18-a91c-63e74099c41a.png)
![Screenshot (214)](https://user-images.githubusercontent.com/105537443/224486683-c5639867-5164-4d31-a4ba-23089e3439d4.png)

**Comment by Srijita-Mandal** [comment]
@priyanka1551 yes. go for it.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
