### ISSUE TITLE
Add Force Unit Convertor

### ISSUE THREAD

**Issue by zugzwang03** [Srijita-Mandal/fix-your-nums#377]
I want to add a Force Unit Convertor to convert various units of force across them under JWOC'23.
This picture here describes the various units clearly: https://images.app.goo.gl/K9FNLV9uD2qKQsuMA

**Comment by Srijita-Mandal** [comment]
@zugzwang03 Go for it.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
