### ISSUE TITLE
Line chart calculator for values

### ISSUE THREAD

**Issue by Saishreekouda** [Srijita-Mandal/fix-your-nums#378]

**Comment by Srijita-Mandal** [comment]
@Saishreekouda Describe some more what you want to do

**Comment by Saishreekouda** [comment]
I would take some input x and y values and then plot a graph on the basis of that

**Comment by Srijita-Mandal** [comment]
@Saishreekouda Yes. go for it.

**Comment by Saishreekouda** [comment]
https://saishreekouda.github.io/fix-your-nums/html_files/graph.html
