### ISSUE TITLE
Want to add some documentation

### ISSUE THREAD

**Issue by Sowham-3098** [Srijita-Mandal/fix-your-nums#38]
1. LICENSE.md
2. contributing.md
3. contributors profile section in README.md

**Comment by Sowham-3098** [comment]
Please assign this to me under JWOC

**Comment by Srijita-Mandal** [comment]
@Sowham-3098 Go for it. Do only `LICENSE.md` and `contributing.md`. Feature point 3 is already assigned to implement.
