### ISSUE TITLE
Tip Calculator(Phase 2)

### ISSUE THREAD

**Issue by priyanka1551** [Srijita-Mandal/fix-your-nums#382]
Tip Calculator will calculates the appropriate amount of tip to give based on the cost of the meal, the quality of service, and the number of people. I want to work on this issue under JWOC @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
