### ISSUE TITLE
Language Translator

### ISSUE THREAD

**Issue by ritika728** [Srijita-Mandal/fix-your-nums#383]
Hey @Srijita-Mandal, I would like to open this issue under JWOC. 
- User can translate the text into any language with just one click.
- user can select the preferred language from all the possible languages (100+ including hindi) available on Google
- after selecting a specific language, user will be able to :
  - again translate the page by choosing new language
  - showing the original language
  - turn off the translation for that site

I will add this feature in the navbar of all the pages. Kindly assign

**Comment by Srijita-Mandal** [comment]
@ritika728 yes. Go for it.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC
