### ISSUE TITLE
Surface Area Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#392]
It will calculate the total surface area of 3-d figures like cubes, cuboids, spheres, cones, and cylinders.

for example 
for cylinder
it will take the input radius and height 
and then output the result

for cuboid
it will take input length, breadth, height
and then output the result

for sphere
it will take the input as radius 
and then calculate the result

**Comment by LuckySingh9897** [comment]
I want to work on this issue under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Go for it.
