### ISSUE TITLE
Adding Arithmetic Progression Generator

### ISSUE THREAD

**Issue by pooranjoyb** [Srijita-Mandal/fix-your-nums#402]
## Workflow : 
- The user will enter the nth tern of the series
- First 2, 3 data will be provided
- Subsequently the series will be generated w.r.t given nth term

## I would like to work on this issue under JWOC 2023. Please Assign me. @Srijita-Mandal 😄

**Comment by Srijita-Mandal** [comment]
@pooranjoyb Go for it.
