### ISSUE TITLE
Budget Calculator

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#404]
This calculator helps to calculate budget. It has following features:

- It has option of adding income and expenditure both along with their description.
- It will be responsive.
- User can delete particular income or expenditure.
- User can edit particular income or expenditure.
- Shows total balance 
- Retains the date of income and expenditure as well.

Please assign this issue to me under JWOC.

**Comment by Srijita-Mandal** [comment]
@S-ishita Go for it.

**Comment by S-ishita** [comment]
Please increase the difficulty level , it has many additional features...
