### ISSUE TITLE
Adding Geometric Progression Generator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#408]
I would Like to add a GP generator that is geometric progression generator which will generate the series for the given input.
It will take input first three terms and the nth term
and print the entire series respectively.

for example 
input 
first three terms= 2,4,8
nth terms is 1024

output is= 
2,4,8,16,32,64,128,256,512,1024

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 go for it.
