### ISSUE TITLE
Sum of the series AP and GP

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#425]
In this calculator, there will be two options choose either AP or GP
after choosing 
For Example 
if You choose AP
then you have to input as = a1, d, number of terms
then the calculator will print the sum of N terms of the series.

and if you choose GP
then you have to give input as a1, r ,and the number of terms 
then the calculator will print  the sum of N terms of series

**Comment by LuckySingh9897** [comment]
I want to work on this under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 yes. Go for it.
