### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by ritika728** [Srijita-Mandal/fix-your-nums#431]
Hey @Srijita-Mandal , I would like to open this issue under JWOC.

A frequently asked questions section is a very crucial part of any website. A wish to add this page where the user can get answers to the following questions:

- What is the website all about
- What are its features
- What all technologies do it use and etc.

I'll make it
- same UI as home page
-  add it in navbar of all the pages. 
- responsive for all devices

Kindly assign 😄

**Comment by Srijita-Mandal** [comment]
@ritika728 FAQ section is already present in Contact page. Please find another issue.

**Comment by ritika728** [comment]
Oh okay!
