### ISSUE TITLE
Improving temperature calculator

### ISSUE THREAD

**Issue by Abhilash1781** [Srijita-Mandal/fix-your-nums#45]
Hi ,
I'm Abhilash S Bharadwaj , JWOC '23 contributor .
I would like to improve temperature calculator by including Kelvin conversion . 
Right now only Celsius to Fahrenheit and vice versa is there . Please assign this issue to me . 
Extremely sorry for raising the issue even before commencement of the program 

![kelvin](https://user-images.githubusercontent.com/72621930/219059952-48fb5136-cbe1-4c0d-833d-32a7ebf7be76.png)

**Comment by Srijita-Mandal** [comment]
@Abhilash1781 Go for it. All the best.

**Comment by Srijita-Mandal** [comment]
@priyanka1551 You are assigned for this issue. Go for it and do complete within time.

**Comment by deepbeatz** [comment]
I would like to work under JWOC @Srijita-Mandal

**Comment by priyanka1551** [comment]
> @priyanka1551 You are assigned for this issue. Go for it and do complete within time.

sure di , I will complete the assigned task
