### ISSUE TITLE
Heat Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#450]
IT will Calculate the heat by taking the input as mass, specific Heat, and temperature Difference
for example
input mass= 0.5
specific heat= 4.2
Temperature difference=10
output wil be= 21

I want to work on this under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Implement both.

**Comment by Awesomeasma** [comment]
@Srijita-Mandal 
I would like to work on this under JWOC
