### ISSUE TITLE
Variance Calculator

### ISSUE THREAD

**Issue by ritika728** [Srijita-Mandal/fix-your-nums#454]
Hey @Srijita-Mandal i would like to open this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@ritika728 Please describe your issue.

**Comment by ritika728** [comment]
@Srijita-Mandal I would like to add a calculator which would calculate the variance of a sample/population. I will add a function that will use the formula:

![photo](https://user-images.githubusercontent.com/91181981/225046775-44971bd6-0397-490e-9f0d-dd6d010f33d3.png)

**Comment by Srijita-Mandal** [comment]
@ritika728 yes. Go for it.
