### ISSUE TITLE
Modify Force Calculator

### ISSUE THREAD

**Issue by zugzwang03** [Srijita-Mandal/fix-your-nums#455]
I feel we can make one force calculator which can do the following operations:

1) Calculate force as F = ma
2) Calculate force as F = p/t
3) Calculate electric force as F = kq1q2/r^2
4) Calculate gravitational force as F = Gm1m2/r2
5) Calculate magnetic force as F = BIl => F = magnetic flux density * length of rod * current 
 
Plus make the page responsive for all devices. As a result, we can also remove the preexisting force and gravitation force calculator from the repo. I can do this under JWOC'23.

**Comment by S-ishita** [comment]
I am already working on F=ma one..it is almost done

**Comment by S-ishita** [comment]
then let me add my calculator..ideally this issue will be valid only when force calculator is added....

**Comment by Awesomeasma** [comment]
@Srijita-Mandal 
I would like to work on this under JWOC
