### ISSUE TITLE
Create a team page

### ISSUE THREAD

**Issue by khushimarothi** [Srijita-Mandal/fix-your-nums#458]
I want to create a separate team page as the team section in the about us is making about page look so long and filled.
please assign under jwoc

**Comment by Srijita-Mandal** [comment]
@khushimarothi I don't think it is necessary. The navbar already has 6 items. Adding more items not be looking good.

**Comment by khushimarothi** [comment]
What if the link to team page be added in footer where it is  written team.

**Comment by Srijita-Mandal** [comment]
@khushimarothi ok go for it.
