### ISSUE TITLE
Modulo Calculator producing wrong results

### ISSUE THREAD

**Issue by anurag8546** [Srijita-Mandal/fix-your-nums#459]
Modulo Calculator inside the calculator is giving wrong output for negative numbers. It needs to be fixed!!
<img width="728" alt="Screenshot 2023-03-14 191439" src="https://user-images.githubusercontent.com/76533034/225021043-800c5305-b8fb-49ed-8832-3287a80017bd.png">

**Comment by Srijita-Mandal** [comment]
@anurag8546 Yes. go for it.

**Comment by Srijita-Mandal** [comment]
@anurag8546 Make this PR asap or I'll unassign you from 2nd one. Don't make more than one issue at a time.

**Comment by Awesomeasma** [comment]
@Srijita-Mandal
I would like to work on this under JWOC

**Comment by anurag8546** [comment]
I've made a PR for the modulo calculator along with the word counter. Please look into it!
