### ISSUE TITLE
Sum of n Fibonacci numbers  and find the nth Fibonacci Number

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#462]
I want to make the calculator that will find the nth number fibonacci number and  then find the sum of n fibonacci numbers.
for example

input ==5
output=
Sum= 7
nth number= 3
I want to work on this under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Go for it.
