### ISSUE TITLE
Acceleration Due to Gravity Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#473]
As we know that the acceleration  due to gravity differs with an increase in height and a decrease in depth
So I want to make a Calculator that has two methods -
method1== (Height Change)
then calculate the acceleration due to gravity (g)with height h

Method 2==(Depth Change)
then Calculate the acceleration due to gravity (g) with depth d

Calculate the acceleration due to gravity in terms of (g) where g is the acceleration due to gravity at the surface,

I want to work on this under JWOC.

**Comment by LuckySingh9897** [comment]
The result will be like (9g) or (0.5g) so that we can compare it also with the surface.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 go for it.
