### ISSUE TITLE
Mechanical Energy Calculator

### ISSUE THREAD

**Issue by ritika728** [Srijita-Mandal/fix-your-nums#478]
Hey @Srijita-Mandal , I would like to open this issue under JWOC. 
I wish to add a calculator to add the calculator for mechanical energy. It is implemented by:
- Firstly, calculating the kinetic energy using the formula:
- ![p1](https://user-images.githubusercontent.com/91181981/225112781-e9032b58-6548-43c9-944d-b1f400fd71c7.png)
- The, calculating the potential energy using the formula:
![p2](https://user-images.githubusercontent.com/91181981/225113217-a1ea0717-7db6-42a4-ad7b-ea82e7dc67ee.jpg)

- At last, calculating the mechanical energy using :
 
![p3](https://user-images.githubusercontent.com/91181981/225112910-6b2bb1cf-c329-4e36-81c2-3b22e2fc5522.png)

Kindly assign 😀

**Comment by Srijita-Mandal** [comment]
@ritika728 Go for it.
