### ISSUE TITLE
[Enhancement] Adding Vector Calculator

### ISSUE THREAD

**Issue by pooranjoyb** [Srijita-Mandal/fix-your-nums#480]
## Workflow : 
- The user will enter the vectors in the form `(xi + yj + zk)`
- He/She will be prompted for `Addition`,` Subtration`, `Dot `or `Cross Product` among the vectors. 
- Subsequently the result will be displayed after calculation

## I would like to work on this issue under JWOC 2023. Please Assign me. @Srijita-Mandal 😄

**Comment by Srijita-Mandal** [comment]
@pooranjoyb go for it.

**Comment by Awesomeasma** [comment]
@Srijita-Mandal
I would like to work on this under JWOC
