### ISSUE TITLE
Electricity Bill Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#484]
It will calculate the Electricity Bill of your Household
It will take inputs Power consumption, usage time, and Cost per unit.

For example
input =

Power consumption= 400W
Usage Time = 4Hr
Cost pr unit = 5

Output will be=  Rs 8

I want to work on this under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 go for it.

**Comment by Awesomeasma** [comment]
@Srijita-Mandal 
I would like to work on this under JWOC
