### ISSUE TITLE
Nth term calculator for AP and GP

### ISSUE THREAD

**Issue by anurag8546** [Srijita-Mandal/fix-your-nums#487]
I would like to add a new calculator called Nth term calculator. It will take  input as required in the particular series and produce the Nth term if possible else throw an error. 
Also it'll be kept updated for other series. 
@Srijita-Mandal would like to work on it under JWOC.

**Comment by Srijita-Mandal** [comment]
@anurag8546 Go for it.

**Comment by Srijita-Mandal** [comment]
@anurag8546 First complete your issue #459
