### ISSUE TITLE
Improve Force Calculator

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#488]
In Force Calculator, add proper units to the input placeholders respective to the output, so that user can easily understand inputs are given in which units.

**Comment by Laxmankohar** [comment]
@Srijita-Mandal ,I would like to work on this issue under jwoc. Can you assign it to me?

**Comment by Awesomeasma** [comment]
@Srijita-Mandal 
I would like to work on this under JWOC

**Comment by Srijita-Mandal** [comment]
@Laxmankohar go for it.
