### ISSUE TITLE
Add Fractional Calculator

### ISSUE THREAD

**Issue by Laxmankohar** [Srijita-Mandal/fix-your-nums#489]
This calculator would allow users to add, subtract, multiply, and divide fractions. It could also simplify fractions and convert between mixed numbers and improper fractions.
 
 @Srijita-Mandal ,I would like to work on this issue under jwoc. Can you assign it to me?

**Comment by Srijita-Mandal** [comment]
@Laxmankohar go for it.

**Comment by Awesomeasma** [comment]
@Srijita-Mandal 
I would like to work on this under JWOC
