### ISSUE TITLE
Power of Lens Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#494]
There are two types of lenses concave and convex I want to make a calculator that will calculate
the power of both type of lens separately
Implementation =
first, we choose which type of lens it is
secondly, we take the input as the magnification of the image  and the distance of the object 
first we will calculate the distance of image
then calculate will calculate the focal length of the lens and from which it calculates the power.

For example
if we choose convex lens
input =m= -1
u=20
output will be = power= +10D.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 go for it.
