### ISSUE TITLE
Polynomial derivative calculator (EDIT: algebraic expression)

### ISSUE THREAD

**Issue by EmberTSeal** [Srijita-Mandal/fix-your-nums#51]
Proposed feature: A calculator to calculate derivative of a user-input polynomial.

EDIT: I meant 'algebraic expressions' and not polynomial. (I made a mistake in the mathematical term. Sorry!)

**Comment by EmberTSeal** [comment]
I would like to work on this issue as a contributor under JWOC.

**Comment by Srijita-Mandal** [comment]
@EmberTSeal Go for it. Make sure to create separate branch and do `git pull` before make a PR. All the best.

**Comment by priyanka1551** [comment]
I would like to work under JWOC @Srijita-Mandal

**Comment by deepbeatz** [comment]
I would like to work under JWOC @Srijita-Mandal
