### ISSUE TITLE
Capacitance Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#510]
It will have two choices series and parallel 
and they ask for three inputs as the value of each capacitance.
For example
method 1 series
input = 2,4, 6
Output = 1.09 uf
similarly for parallel
I want to work on this under JWOC.

**Comment by LuckySingh9897** [comment]
I can also one more method as there is one more formula to calculate capacitance by taking Area and distance of plates 
as input 
If you say so I can implement both  in same calculator.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 go for it. Implement both in same calculator.
