### ISSUE TITLE
Add counter animation 

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#515]
I want to add counter animation which will show the number of users of our website , people benefitted from our website etc on  about us page...

Please assign this issue to me under JWOC
A reference is shown below:

https://user-images.githubusercontent.com/104543751/225347290-351f3b25-eb70-4eaf-9dbb-403dc14609f3.mp4

**Comment by Srijita-Mandal** [comment]
@S-ishita yes. go for it.
