### ISSUE TITLE
Fixed Header Throughout the Website.

### ISSUE THREAD

**Issue by rohhhit31** [Srijita-Mandal/fix-your-nums#52]

**Comment by rohhhit31** [comment]
Assign me this issue I can fix this.

**Comment by Shantanu-Meta** [comment]
Hey @Srijita-Mandal , I would like to contribute in this issue, could you please assign me this issue under JWOC 2k23 ?

**Comment by manya0210** [comment]
Hello @Srijita-Mandal ...I want to work on this issue under jwoc
