### ISSUE TITLE
Sum of n Natural number calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#520]
this calculator will include many feature like
1) sum of n natural numbers
2)sum of square of n natural numbers
3) sum of cube of n natural numbers
4)sum of n even numbers
5) sum of n odd numbers

It will choice what you want to calculate
I want to work on this under JWOC.

**Comment by LuckySingh9897** [comment]
It will take n as input and will ask you about what you want to calculate .

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Go for it.
