### ISSUE TITLE
Add Statistics Calculator

### ISSUE THREAD

**Issue by Laxmankohar** [Srijita-Mandal/fix-your-nums#527]
This calculator takes input as values separated by commas and when the user click on the click button , it will calculate the following:
1. No. of items
2. Mean
3. Median
4. Mode
5. Range
6. Standard Deviation
7. Draw the frequency distribution table.

@Srijita-Mandal , I would like to work on this issue under Jwoc. Can you assign it to me?

**Comment by Srijita-Mandal** [comment]
@Laxmankohar Mean. median. mode, range, standard deviation these calculators are already added. You can make frequency distribution table.

**Comment by Laxmankohar** [comment]
ok.

**Comment by Srijita-Mandal** [comment]
@Laxmankohar okay. go for it.
