### ISSUE TITLE
Fix the present date's problem in Age calculator

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#53]
In Age Calculator, if today's date is given, it shows a invalid date. This needed to be fixed. 
1.  For today's date, it should show `Welcome! It's your first day on earth!!`
2.  For dates after today, leave it as it it- `invalid date`

**Comment by Laxmankohar** [comment]
Hey @Srijita-Mandal , I would like to work on this issue under JWOC. Can you please assign it?

**Comment by Srijita-Mandal** [comment]
@Laxmankohar Yes. Go for it.

**Comment by Laxmankohar** [comment]
Hey @Srijita-Mandal , Please have a look.

![image](https://user-images.githubusercontent.com/73365025/219363990-f92b1b7a-556f-48f6-955f-14251be6116a.png)
![image](https://user-images.githubusercontent.com/73365025/219364003-348566d9-34aa-4388-98f7-e5b2e8bf19e6.png)

**Comment by Srijita-Mandal** [comment]
@Laxmankohar 
Why the date is in `MM/DD/YYYY` format? Please keep the date in same format as it is now. This is look like this now.
![Screenshot 2023-02-16 183659](https://user-images.githubusercontent.com/84610348/219373698-5cd907bc-cf0a-4107-bbf6-ce7176ccde4d.png)

**Comment by Laxmankohar** [comment]
> @Laxmankohar Why the date is in `MM/DD/YYYY` format? Please keep the date in same format as it is now. This is look like this now. ![Screenshot 2023-02-16 183659](https://user-images.githubusercontent.com/84610348/219373698-5cd907bc-cf0a-4107-bbf6-ce7176ccde4d.png)

I have changed nothing regarding this.This is happening because the format of date in my system is different and in your system is different. The format of date is always picked from your system by default.So, if you run this program in your system it will show DD-MM-YYYY format.

**Comment by Laxmankohar** [comment]
Should i make a pull request?
