### ISSUE TITLE
Modulus of Elasticity Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#543]
There are three  modulus of Elasticity ==
Youngs  modulus
Shear modulus
Bulk Modulus

I want to make  a calculator that will calculate all three by taking the input as required by the formula

I want to work on this under JWOC.

**Comment by LuckySingh9897** [comment]
There will be three options to choose from depending on what you want to calculate
for example  if you choose 
Youngs modulus
it will ask input as stress and strain
and then calculate the modulus of elasticity

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Go for it.
