### ISSUE TITLE
Moment of Inertia Calculator

### ISSUE THREAD

**Issue by LuckySingh9897** [Srijita-Mandal/fix-your-nums#557]
It will calculate the moment of Inertia of Different rigid bodies
In this calculator, user will have choices Like--
 Rod, 
 Disc 
Solid Sphere  
Hollow Sphere  
Cylinder  
Ring .

After selecting the rigid body it will take the input as Mass and radius 
and in the case of rod it will take  the input as Mass and length.

I want to make a calculator that will have all the above mentioned features under JWOC.

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 go for it.
