### ISSUE TITLE
Centre of Mass Calculator

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#559]
It will calculate centre of mass of different systems:
Rectangle,triangle,ring,disc,solid hemisphere etc

After selecting the system it will take the input as radius in case of ring
and in the case of triangle it will take the input as base and height and similarly for the others as well

I will implement these in single calculator. Please assign this issue to me under JWOC

**Comment by Srijita-Mandal** [comment]
@S-ishita go for it.

**Comment by S-ishita** [comment]
Please increase the difficulty level of this ..
