### ISSUE TITLE
Add HCF calculator

### ISSUE THREAD

**Issue by pritika163** [Srijita-Mandal/fix-your-nums#56]
I want to add a hcf calculator.
I want to work on this issue under JWOC , please assign it to me.

**Comment by Srijita-Mandal** [comment]
@pritika163 Yes. Go for it. 
Do both HCF and LCM of two given numbers.
Make only one new section `HCF-LCM Calculator` and do your changes in a separate `branch` and make sure to `git pull` before PR.
All the best!
