### ISSUE TITLE
Coefficient of friction calculator

### ISSUE THREAD

**Issue by ritika728** [Srijita-Mandal/fix-your-nums#567]
Hey @Srijita-Mandal , please assign me this issue under JWOC. I'll add a calculator to calculate the coefficient of friction (fr) which is a number that is the ratio of the resistive force of friction (Fr) divided by the normal or perpendicular force (N) pushing the objects together. I would like to work on this. Kindly assign 😀

**Comment by Srijita-Mandal** [comment]
@ritika728 go for it.
