### ISSUE TITLE
Adding the discount feature in the calculator.

### ISSUE THREAD

**Issue by goresai19** [Srijita-Mandal/fix-your-nums#57]
## Adding an additional feature to calculate the Discount 

In this I will add an additional feature to calculate the discount on an original price which is given by the user and the discount percentage which is also given by user and in the output I will display the final price after the discount.
I would like to work on this feature under the JWOC.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC
