### ISSUE TITLE
Adding name inside of each calculator

### ISSUE THREAD

**Issue by Shantanu-Meta** [Srijita-Mandal/fix-your-nums#59]
Hey @Srijita-Mandal , there can be few cases: 
1. user want to calculate bmi, but somehow if they click just adjacent calc. of bmi they won't be notified that it is not a clc. for bmi, right ?
so it will be difficult to use,
**so we can put the separated name for each calc. inside them.** 
*have a look:*
![image](https://user-images.githubusercontent.com/117648930/219387282-34770937-1f71-4bd9-92cc-ce34e3617234.png)

*previously:* 
![image](https://user-images.githubusercontent.com/117648930/219387487-c46ef06b-c4ec-45b0-99d8-0a8b57ba1cb3.png)

**Comment by Shantanu-Meta** [comment]
So can you please assign me this issue, I will fix this problem for all the pages. After all we have to give the user smooth experience.

**Comment by Srijita-Mandal** [comment]
@Shantanu-Meta Yes, you go for it.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by SarveshGholap** [comment]
I want to work on this issue under jwoc
