### ISSUE TITLE
Add Body fat percentage calculator

### ISSUE THREAD

**Issue by Viveksati5143** [Srijita-Mandal/fix-your-nums#599]
Please assign me this issue @S-ishita

**Comment by Srijita-Mandal** [comment]
@Viveksati5143 give some description

**Comment by Viveksati5143** [comment]
A body fat percentage calculator is a tool that estimates the percentage of body fat based on certain measurements, such as height, weight, and body circumference. It is used to determine the amount of fat versus muscle mass in the body and can be a useful tool for assessing overall health and fitness levels. Body fat percentage calculators can provide an estimate of body fat percentage, but it's important to note that they are not a substitute for a medical diagnosis or advice from a healthcare professional. @Srijita-Mandal

**Comment by Viveksati5143** [comment]
@Srijita-Mandal ???

**Comment by Viveksati5143** [comment]
Only 1 hour is left for jwoc make this my last issue
