### ISSUE TITLE
Improving the temperature calculator 

### ISSUE THREAD

**Issue by Abhilash1781** [Srijita-Mandal/fix-your-nums#6]
Hi , 
I'm Abhilash S Bharadwaj , JWOC '23 contributor . 
I would like to improve temperature calculator by including Kelvin conversion . Right now only Celsius to Fahrenheit and vice versa is there . Please assign this issue to me  

![kelvin](https://user-images.githubusercontent.com/72621930/218242609-fff3381b-caf4-4b8b-8ccf-f0602b644d68.png)

**Comment by Srijita-Mandal** [comment]
@Abhilash1781 Please raise your issues and solve after the contribution period starts. I can't assign as it is created before.

**Comment by PrachiSingh66** [comment]
Hii, I want to work on this issue under JWOC so please assign it to me.
Thank you

**Comment by Codey001** [comment]
i would like to work on the issue
