### ISSUE TITLE
[Enhancement]Font family of age calc. have to be changed

### ISSUE THREAD

**Issue by Shantanu-Meta** [Srijita-Mandal/fix-your-nums#60]
in age calc, the font is times new roman which is not matching  with others *ubuntu*, 
It has to be changed to ubuntu,
previously: 
![image](https://user-images.githubusercontent.com/117648930/219391704-5fe36c98-b02e-45ad-ab8c-5b7ef1930dd8.png)

look: 
![image](https://user-images.githubusercontent.com/117648930/219391525-bfd5c722-e5a8-4fc5-9bf5-add191d37c1e.png)

**Comment by Srijita-Mandal** [comment]
@Shantanu-Meta Go for it. Not only in age calculator, the same font problem is in Bitwise Calculator, Days-Month Calculator, Currency converter and some other. Fix all these fonts.

**Comment by Shantanu-Meta** [comment]
Okay I will finish it up

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@Shantanu-Meta Make PR with your commits.

**Comment by Shantanu-Meta** [comment]
hey I have made the pr, kindly verify it
