### ISSUE TITLE
Validate contact us form

### ISSUE THREAD

**Issue by khushimarothi** [Srijita-Mandal/fix-your-nums#601]
I want to validate the contact us form 
Please assign under jwoc

**Comment by Srijita-Mandal** [comment]
@khushimarothi what type of validation?

**Comment by khushimarothi** [comment]
Validation using JavaScript. Instead of required. The color of input box will turn red and a message will be shown which will ask the user to fill the details correctly

**Comment by Srijita-Mandal** [comment]
@khushimarothi go for it.
