### ISSUE TITLE
Retirement savings calculator

### ISSUE THREAD

**Issue by Viveksati5143** [Srijita-Mandal/fix-your-nums#612]
A Retirement Savings Calculator is a tool that helps individuals estimate how much they should save each month to achieve their retirement goals. It takes into account factors such as the individual's current age, desired retirement age, expected retirement income, expected expenses in retirement, and the expected rate of return on investments.

**Comment by Viveksati5143** [comment]
@S-ishita How about this issue?

**Comment by S-ishita** [comment]
Dude u tagging wrong person..

**Comment by Viveksati5143** [comment]
oops sorry🤣🤣

**Comment by Viveksati5143** [comment]
@Srijita-Mandal ???

**Comment by Srijita-Mandal** [comment]
@Viveksati5143 go for it
