### ISSUE TITLE
Enter key doesn't work for submission

### ISSUE THREAD

**Issue by D3vilGhost** [Srijita-Mandal/fix-your-nums#67]
hi!
Myself Kartikey Agarwal, JWOC'23 Contributor.
In whole calculator, the enter key doesn't work for submission of values. its kinda tough for laptop or desktop users to scroll their mouse to the submission button after typing on keyboard.
also what i have found is pressing enter key refreshes the page leading to loss of the value inserted by user.

**Comment by Srijita-Mandal** [comment]
@D3vilGhost Go for it. Just implement the feature to Submit by pressing Enter key. Implement it for all the calculators are added till now.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC
