### ISSUE TITLE
Improve Roman-Integer Converter

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#70]
There are some problems to fix in Roman-Integer converter.
1.  For roman to int, only uppercase characters are supported. It should support and shows result both in uppercase and lowercase.
2.  If wrong input is given, i.e- roman is given as input while converting int to roman   and   integer is given as input while converting roman to int, it should throw an error msg `Please provide correct input`
3.  Add favicon.

**Comment by SarveshGholap** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@SarveshGholap Go for it.
