### ISSUE TITLE
Copy To Clipboard Feauture

### ISSUE THREAD

**Issue by psykat1116** [Srijita-Mandal/fix-your-nums#72]
There is no copy to clipboard feature by which we can directly copy it by simply clicking it. Please assign me so that i can fix it.
![Untitled](https://user-images.githubusercontent.com/95569573/219597019-43c321d1-d60e-41f1-9cce-05e70f83011d.jpg)

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@psykat1116 Go for it. Make this copy only the numerical in the answer. As example, don't copy `Decimal=85` , instead copy only `85`.
Create separate branch, and `git pull` from main repo.
All the best.

**Comment by deepbeatz** [comment]
@Srijita-Mandal I want to work on this under JWOC

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @Srijita-Mandal

**Comment by manya0210** [comment]
I want to work on this issue under jwoc...

**Comment by vatan-prakash** [comment]
I want to work on this issue under jwoc...

**Comment by SarveshGholap** [comment]
I want to work on this issue under jwoc
