### ISSUE TITLE
Binomial Coefficient Calculator

### ISSUE THREAD

**Issue by S-ishita** [Srijita-Mandal/fix-your-nums#78]
The Binomial Coefficient Calculator is used to calculate the binomial coefficient C(n, k) of two given natural numbers n and k .

![Screenshot from 2023-02-17 18-05-18](https://user-images.githubusercontent.com/104543751/219655149-668d0f18-d462-4cf7-9e79-10564c49dc9f.png)

**Comment by S-ishita** [comment]
I want to work on this issue under JWOC.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@S-ishita I have updated the home page. So, take `git pull` from updated repo and make necessary changes.
