### ISSUE TITLE
Trigonometric Calculator

### ISSUE THREAD

**Issue by EmberTSeal** [Srijita-Mandal/fix-your-nums#84]
Proposed Feature: 

A trigonometric calculator with the following features:
- user inputs an angle in degree or radian
- calculate sin, cos, tan, sec, cosec and cot of the given angle 
- user has the ability to choose which trig functions to be calculated (from a checklist)
- appropriate form validations for empty or invalid input

**Comment by EmberTSeal** [comment]
I would like to work on this issue as a contributor under JWOC.

**Comment by Srijita-Mandal** [comment]
@EmberTSeal I have updated the home page. So, take `git pull` from updated repo and make necessary changes.

**Comment by EmberTSeal** [comment]
Okay, thanks for the heads up.

**Comment by bcsamrudh** [comment]
@Srijita-Mandal . Can I contribute.

**Comment by deepbeatz** [comment]
@Srijita-Mandal I want to work on this under JWOC

**Comment by priyanka1551** [comment]
I work to work on this issue under JWOC @Srijita-Mandal

**Comment by EmberTSeal** [comment]
Hello, just an update: I'm actively working on this issue and I'll surely complete it by tomorrow night.

**Comment by LuckySingh9897** [comment]
I would like to work on this issue under JWOC.
