### ISSUE TITLE
Improving folder structure

### ISSUE THREAD

**Issue by AshutoshSingh2021** [Srijita-Mandal/fix-your-nums#85]
Restructure the files and folders of the project. I will create separate files for HTML, CSS, and JS and link them to their proper place so that the code of the project will be easily understood by the contributors.

Please assign this issue to me under JWOC. I want to fix this problem.

**Comment by AshutoshSingh2021** [comment]
Please assign this issue to me under JWOC. I want to fix this problem.

**Comment by AshutoshSingh2021** [comment]
@Srijita-Mandal please add the appropriate labels for this issue.

**Comment by deepbeatz** [comment]
@Srijita-Mandal I want to work on this under JWOC
