### ISSUE TITLE
An animated Landing page for website on opening 

### ISSUE THREAD

**Issue by AK-shat-JAIN** [Srijita-Mandal/fix-your-nums#86]
The landing page looks very normal
Want to add an animation effect in it such that the text "Fix your nums" will animate and come like in this website
https://ak-shat-jain.github.io/FoodGenix/
that's also created by me

**Comment by Srijita-Mandal** [comment]
> The landing page looks very normal Want to add an animation effect in it such that the text "Fix your nums" will animate and come like in this website https://ak-shat-jain.github.io/FoodGenix/ that's also created by me

Like the first appearance of the website name?

**Comment by AK-shat-JAIN** [comment]
Yes thats look awesome

**Comment by AK-shat-JAIN** [comment]
like in this https://click-the-edible-game.netlify.app/

**Comment by Srijita-Mandal** [comment]
@AK-shat-JAIN Go for it. Make the design according to the home page theme.

**Comment by AK-shat-JAIN** [comment]
Hello Ma'am @Srijita-Mandal Thanks for assigning this task to me

**Comment by AK-shat-JAIN** [comment]
mam, please add appropriate tag!!
