### ISSUE TITLE
Add Hexadecimal-Octal-decimal-binary conversions

### ISSUE THREAD

**Issue by Vinay-Singh-Chauhan** [Srijita-Mandal/fix-your-nums#9]
Currently the project supports decimal-binary conversions only. I would add Hexadecimal and octal conversions also. Please assign this issue to me.

**Comment by Srijita-Mandal** [comment]
@Vinay-Singh-Chauhan Please raise your issues after the contribution period starts. I can't assign as it is created before.

**Comment by Vinay-Singh-Chauhan** [comment]
Okay. Thanks for letting me know. I'll do the needful.
