### ISSUE TITLE
Data converter (B, KB, MB, GB, TB)

### ISSUE THREAD

**Issue by codingis4noobs2** [Srijita-Mandal/fix-your-nums#90]
I want to work on this issue under JWOC.

**Comment by Priyamakeshwari** [comment]
i want to work on this issue under JWOC

**Comment by neokd** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@codingis4noobs2 Go for it.

**Comment by deepbeatz** [comment]
@Srijita-Mandal I want to work on this under JWOC
