### ISSUE TITLE
OverScrolling of page

### ISSUE THREAD

**Issue by Laxmankohar** [Srijita-Mandal/fix-your-nums#91]
when inside any calculator, the  page starts overscrolling which  may cause poor user experince.
I would like to work on this issue under JWOC. Can you please assign it ot me?

![image](https://user-images.githubusercontent.com/73365025/219854447-479ae3f0-1f2c-4065-9c47-2e5e660c3e71.png)

**Comment by Srijita-Mandal** [comment]
@Laxmankohar yes! Go for it.
