### ISSUE TITLE
Change the title of the website to 'Fix your nums'

### ISSUE THREAD

**Issue by Arbtrage** [Srijita-Mandal/fix-your-nums#92]
@Srijita-Mandal ,
I would like to change the title of the website from ' Home' to ' Fix your nums' .
Please assign me this issue under Jwoc.

**Comment by VaibhavTalkhande** [comment]
Can work under jwoc

**Comment by Srijita-Mandal** [comment]
@Arbtrage Go fir it.

**Comment by Arbtrage** [comment]
Okay
