### ISSUE TITLE
Change The Appearance Of Home Page And Correct The Format Of The Tittle 

### ISSUE THREAD

**Issue by swarnade** [Srijita-Mandal/fix-your-nums#95]
Change The Appearance Of Home Page And Correct The Format Of The Tittle. the Text Alignment Is little In-Correct And Text Format #JWOC

**Comment by Srijita-Mandal** [comment]
@swarnade Go for it. But don't make the design too much complicated.

**Comment by deepbeatz** [comment]
@Srijita-Mandal I want to work on this under JWOC

**Comment by swarnade** [comment]
Issue Resolved.....
