### ISSUE TITLE
Add a home icon

### ISSUE THREAD

**Issue by zugzwang03** [Srijita-Mandal/fix-your-nums#96]
I want to add a home icon in every calculator specific page, so that upon clicking that, the user can return back to the home page.
I want to make this contribution under JWOC'23.

I want to add the icon somewhere at this place ...
![image](https://user-images.githubusercontent.com/95460021/219867548-95afc3c0-bdb2-4433-90c1-3be9e8f39ded.png)

**Comment by Srijita-Mandal** [comment]
@zugzwang03 Go for it. Take `git pull` from updated repo before you make a PR.

**Comment by deepbeatz** [comment]
I want to work on this under JWOC
